// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwF-YJnDO4V_mvPa4wDw5CZ1uipaC5H44',
    appId: '1:922774400558:android:cd8e2fa71bd9f7955579bf',
    messagingSenderId: '922774400558',
    projectId: 'adhd-d1c17',
    storageBucket: 'adhd-d1c17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo26gb6NMao1JiZ9WgBk1j3k8OOj2uSOw',
    appId: '1:922774400558:ios:c11c30ae16056fb75579bf',
    messagingSenderId: '922774400558',
    projectId: 'adhd-d1c17',
    storageBucket: 'adhd-d1c17.appspot.com',
    androidClientId: '922774400558-6tcuncn70g3o9554n5g43r2lhdvbv9jd.apps.googleusercontent.com',
    iosClientId: '922774400558-n18r3mo9rm20t18tdgadoancgbni6uf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.newAdhd',
  );
}
