/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String activities = "assets/images/activities.png";
  static const String advisors = "assets/images/advisors.png";
  static const String doc1 = "assets/images/doc1.jpg";
  static const String doc2 = "assets/images/doc2.jpg";
  static const String doc3 = "assets/images/doc3.jpg";
  static const String doc4 = "assets/images/doc4.jpg";
  static const String doc5 = "assets/images/doc5.jpg";
  static const String doc6 = "assets/images/doc6.jpg";
  static const String googleImg = "assets/images/googleImg.png";
  static const String icimg = "assets/images/icimg.png";
  static const String qrCode = "assets/images/qrCode.jpg";
}
